// config_test.go - Configuration Unit Tests
//
// This file contains unit tests for the config package which handles
// application configuration loading from environment variables and files.
//
// # Test Coverage
//
// The tests cover the following configuration sections:
//   - ServerConfig: HTTP server settings (port, timeouts)
//   - DatabaseConfig: Database connection settings
//   - JWTConfig: JWT authentication settings
//   - RateLimitConfig: Rate limiting settings
//   - TelemetryConfig: TelemetryFlow SDK settings
//   - LogConfig: Logging configuration
//
// # Configuration Loading
//
// Tests verify both default values and environment variable overrides
// to ensure proper configuration in different deployment environments.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package config_test

import (
	"os"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/telemetryflow/order-service/internal/infrastructure/config"
)

// =============================================================================
// Config Struct Tests
//
// Tests for configuration struct field population and defaults.
// =============================================================================

// TestConfig_Structs verifies individual config struct field assignments.
func TestConfig_Structs(t *testing.T) {
	t.Run("ServerConfig has correct defaults", func(t *testing.T) {
		cfg := config.ServerConfig{
			Port:         "8080",
			ReadTimeout:  15 * time.Second,
			WriteTimeout: 15 * time.Second,
		}

		assert.Equal(t, "8080", cfg.Port)
		assert.Equal(t, 15*time.Second, cfg.ReadTimeout)
		assert.Equal(t, 15*time.Second, cfg.WriteTimeout)
	})

	t.Run("DatabaseConfig has all fields", func(t *testing.T) {
		cfg := config.DatabaseConfig{
			Driver:          "postgres",
			Host:            "localhost",
			Port:            "5432",
			Name:            "orders",
			User:            "postgres",
			Password:        "secret",
			SSLMode:         "disable",
			MaxOpenConns:    25,
			MaxIdleConns:    5,
			ConnMaxLifetime: 5 * time.Minute,
			Debug:           true,
		}

		assert.Equal(t, "postgres", cfg.Driver)
		assert.Equal(t, "localhost", cfg.Host)
		assert.Equal(t, "5432", cfg.Port)
		assert.Equal(t, "orders", cfg.Name)
		assert.Equal(t, "postgres", cfg.User)
		assert.Equal(t, "secret", cfg.Password)
		assert.Equal(t, "disable", cfg.SSLMode)
		assert.Equal(t, 25, cfg.MaxOpenConns)
		assert.Equal(t, 5, cfg.MaxIdleConns)
		assert.Equal(t, 5*time.Minute, cfg.ConnMaxLifetime)
		assert.True(t, cfg.Debug)
	})

	t.Run("JWTConfig has all fields", func(t *testing.T) {
		cfg := config.JWTConfig{
			Secret:            "test-secret",
			Expiration:        24 * time.Hour,
			RefreshExpiration: 168 * time.Hour,
		}

		assert.Equal(t, "test-secret", cfg.Secret)
		assert.Equal(t, 24*time.Hour, cfg.Expiration)
		assert.Equal(t, 168*time.Hour, cfg.RefreshExpiration)
	})

	t.Run("RateLimitConfig has all fields", func(t *testing.T) {
		cfg := config.RateLimitConfig{
			Requests: 100,
			Window:   1 * time.Minute,
		}

		assert.Equal(t, 100, cfg.Requests)
		assert.Equal(t, 1*time.Minute, cfg.Window)
	})

	t.Run("TelemetryConfig has all fields", func(t *testing.T) {
		cfg := config.TelemetryConfig{
			APIKeyID:       "tfk_test",
			APIKeySecret:   "tfs_test",
			Endpoint:       "localhost:4317",
			ServiceName:    "order-api",
			ServiceVersion: "1.1.1",
		}

		assert.Equal(t, "tfk_test", cfg.APIKeyID)
		assert.Equal(t, "tfs_test", cfg.APIKeySecret)
		assert.Equal(t, "localhost:4317", cfg.Endpoint)
		assert.Equal(t, "order-api", cfg.ServiceName)
		assert.Equal(t, "1.1.1", cfg.ServiceVersion)
	})

	t.Run("LogConfig has all fields", func(t *testing.T) {
		cfg := config.LogConfig{
			Level:  "info",
			Format: "json",
		}

		assert.Equal(t, "info", cfg.Level)
		assert.Equal(t, "json", cfg.Format)
	})
}

func TestConfig_Complete(t *testing.T) {
	t.Run("full Config struct", func(t *testing.T) {
		cfg := config.Config{
			Server: config.ServerConfig{
				Port:         "8080",
				ReadTimeout:  15 * time.Second,
				WriteTimeout: 15 * time.Second,
			},
			Database: config.DatabaseConfig{
				Driver:          "postgres",
				Host:            "localhost",
				Port:            "5432",
				Name:            "orders",
				User:            "postgres",
				Password:        "password",
				SSLMode:         "disable",
				MaxOpenConns:    25,
				MaxIdleConns:    5,
				ConnMaxLifetime: 5 * time.Minute,
			},
			JWT: config.JWTConfig{
				Secret:            "secret",
				Expiration:        24 * time.Hour,
				RefreshExpiration: 168 * time.Hour,
			},
			RateLimit: config.RateLimitConfig{
				Requests: 100,
				Window:   1 * time.Minute,
			},
			Telemetry: config.TelemetryConfig{
				APIKeyID:       "tfk_test",
				APIKeySecret:   "tfs_test",
				Endpoint:       "localhost:4317",
				ServiceName:    "order-api",
				ServiceVersion: "1.1.1",
			},
			Log: config.LogConfig{
				Level:  "info",
				Format: "json",
			},
		}

		assert.Equal(t, "8080", cfg.Server.Port)
		assert.Equal(t, "postgres", cfg.Database.Driver)
		assert.Equal(t, "secret", cfg.JWT.Secret)
		assert.Equal(t, 100, cfg.RateLimit.Requests)
		assert.Equal(t, "tfk_test", cfg.Telemetry.APIKeyID)
		assert.Equal(t, "info", cfg.Log.Level)
	})
}

// =============================================================================
// Config Load Tests
// =============================================================================

func TestConfig_Load(t *testing.T) {
	t.Run("loads config with defaults", func(t *testing.T) {
		// Clear any existing env vars
		envVars := []string{
			"SERVER_PORT",
			"DB_DRIVER",
			"DB_HOST",
			"DB_PORT",
			"DB_NAME",
			"DB_USER",
			"DB_PASSWORD",
			"JWT_SECRET",
			"TELEMETRYFLOW_API_KEY_ID",
			"TELEMETRYFLOW_API_KEY_SECRET",
		}
		for _, v := range envVars {
			_ = os.Unsetenv(v)
		}

		cfg, err := config.Load()

		require.NoError(t, err)
		require.NotNil(t, cfg)

		// Check defaults
		assert.Equal(t, "8080", cfg.Server.Port)
		assert.Equal(t, "postgres", cfg.Database.Driver)
		assert.Equal(t, "localhost", cfg.Database.Host)
		assert.Equal(t, "5432", cfg.Database.Port)
		assert.Equal(t, "orders", cfg.Database.Name)
		assert.Equal(t, "postgres", cfg.Database.User)
		assert.Equal(t, "disable", cfg.Database.SSLMode)
		assert.Equal(t, 25, cfg.Database.MaxOpenConns)
		assert.Equal(t, 5, cfg.Database.MaxIdleConns)
		assert.Equal(t, 100, cfg.RateLimit.Requests)
		assert.Equal(t, "info", cfg.Log.Level)
		assert.Equal(t, "json", cfg.Log.Format)
	})

	t.Run("loads config from environment variables", func(t *testing.T) {
		// Set test environment variables (t.Setenv auto-cleans up after test)
		t.Setenv("SERVER_PORT", "9000")
		t.Setenv("DB_HOST", "db.example.com")
		t.Setenv("DB_NAME", "test_orders")
		t.Setenv("JWT_SECRET", "env-secret")
		t.Setenv("LOG_LEVEL", "debug")

		cfg, err := config.Load()

		require.NoError(t, err)
		require.NotNil(t, cfg)

		assert.Equal(t, "9000", cfg.Server.Port)
		assert.Equal(t, "db.example.com", cfg.Database.Host)
		assert.Equal(t, "test_orders", cfg.Database.Name)
		assert.Equal(t, "env-secret", cfg.JWT.Secret)
		assert.Equal(t, "debug", cfg.Log.Level)
	})

	t.Run("loads telemetry config from environment", func(t *testing.T) {
		// Set test environment variables (t.Setenv auto-cleans up after test)
		t.Setenv("TELEMETRYFLOW_API_KEY_ID", "tfk_env_test")
		t.Setenv("TELEMETRYFLOW_API_KEY_SECRET", "tfs_env_test")
		t.Setenv("TELEMETRYFLOW_ENDPOINT", "collector.example.com:4317")
		t.Setenv("TELEMETRYFLOW_SERVICE_NAME", "test-service")

		cfg, err := config.Load()

		require.NoError(t, err)
		require.NotNil(t, cfg)

		assert.Equal(t, "tfk_env_test", cfg.Telemetry.APIKeyID)
		assert.Equal(t, "tfs_env_test", cfg.Telemetry.APIKeySecret)
		assert.Equal(t, "collector.example.com:4317", cfg.Telemetry.Endpoint)
		assert.Equal(t, "test-service", cfg.Telemetry.ServiceName)
	})
}

// =============================================================================
// Edge Cases
// =============================================================================

func TestConfig_EdgeCases(t *testing.T) {
	t.Run("config with empty values", func(t *testing.T) {
		cfg := config.Config{}

		assert.Equal(t, "", cfg.Server.Port)
		assert.Equal(t, "", cfg.Database.Driver)
		assert.Equal(t, "", cfg.JWT.Secret)
		assert.Equal(t, 0, cfg.RateLimit.Requests)
	})

	t.Run("config with zero duration", func(t *testing.T) {
		cfg := config.ServerConfig{
			Port:         "8080",
			ReadTimeout:  0,
			WriteTimeout: 0,
		}

		assert.Equal(t, time.Duration(0), cfg.ReadTimeout)
		assert.Equal(t, time.Duration(0), cfg.WriteTimeout)
	})

	t.Run("database config with large connection pool", func(t *testing.T) {
		cfg := config.DatabaseConfig{
			MaxOpenConns: 1000,
			MaxIdleConns: 500,
		}

		assert.Equal(t, 1000, cfg.MaxOpenConns)
		assert.Equal(t, 500, cfg.MaxIdleConns)
	})

	t.Run("rate limit with high requests", func(t *testing.T) {
		cfg := config.RateLimitConfig{
			Requests: 10000,
			Window:   time.Second,
		}

		assert.Equal(t, 10000, cfg.Requests)
		assert.Equal(t, time.Second, cfg.Window)
	})
}

// =============================================================================
// Benchmark Tests
// =============================================================================

func BenchmarkConfig_Load(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_, _ = config.Load()
	}
}

func BenchmarkConfig_Struct(b *testing.B) {
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = config.Config{
			Server: config.ServerConfig{
				Port:         "8080",
				ReadTimeout:  15 * time.Second,
				WriteTimeout: 15 * time.Second,
			},
			Database: config.DatabaseConfig{
				Driver: "postgres",
				Host:   "localhost",
			},
		}
	}
}
