// Package handler provides query handlers for Order entity.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package handler

import (
	"context"

	"github.com/telemetryflow/order-service/internal/application/dto"
	"github.com/telemetryflow/order-service/internal/application/query"
	"github.com/telemetryflow/order-service/internal/domain/repository"
)

// OrderQueryHandler handles queries for Order entity
type OrderQueryHandler struct {
	repo repository.OrderRepository
}

// NewOrderQueryHandler creates a new Order query handler
func NewOrderQueryHandler(repo repository.OrderRepository) *OrderQueryHandler {
	return &OrderQueryHandler{
		repo: repo,
	}
}

// HandleOrderGetByID handles get order by ID query
func (h *OrderQueryHandler) HandleOrderGetByID(ctx context.Context, qry *query.GetOrderByIDQuery) (*dto.OrderResponse, error) {
	entity, err := h.repo.FindByID(ctx, qry.ID)
	if err != nil {
		return nil, err
	}
	return dto.OrderToResponse(entity), nil
}

// HandleOrderGetAll handles get all orders query
func (h *OrderQueryHandler) HandleOrderGetAll(ctx context.Context, qry *query.GetAllOrdersQuery) (*dto.OrderListResponse, error) {
	entities, total, err := h.repo.FindAll(ctx, qry.Offset, qry.Limit)
	if err != nil {
		return nil, err
	}

	responses := make([]*dto.OrderResponse, len(entities))
	for i := range entities {
		responses[i] = dto.OrderToResponse(&entities[i])
	}

	return &dto.OrderListResponse{
		Data:   responses,
		Total:  int(total),
		Offset: qry.Offset,
		Limit:  qry.Limit,
	}, nil
}
