// Package handler provides query handlers for Orderitem entity.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package handler

import (
	"context"

	"github.com/telemetryflow/order-service/internal/application/dto"
	"github.com/telemetryflow/order-service/internal/application/query"
	"github.com/telemetryflow/order-service/internal/domain/repository"
)

// OrderitemQueryHandler handles queries for Orderitem entity
type OrderitemQueryHandler struct {
	repo repository.OrderitemRepository
}

// NewOrderitemQueryHandler creates a new Orderitem query handler
func NewOrderitemQueryHandler(repo repository.OrderitemRepository) *OrderitemQueryHandler {
	return &OrderitemQueryHandler{
		repo: repo,
	}
}

// HandleOrderitemGetByID handles get orderitem by ID query
func (h *OrderitemQueryHandler) HandleOrderitemGetByID(ctx context.Context, qry *query.GetOrderitemByIDQuery) (*dto.OrderitemResponse, error) {
	entity, err := h.repo.FindByID(ctx, qry.ID)
	if err != nil {
		return nil, err
	}
	return dto.OrderitemToResponse(entity), nil
}

// HandleOrderitemGetAll handles get all orderitems query
func (h *OrderitemQueryHandler) HandleOrderitemGetAll(ctx context.Context, qry *query.GetAllOrderItemsQuery) (*dto.OrderitemListResponse, error) {
	entities, total, err := h.repo.FindAll(ctx, qry.Offset, qry.Limit)
	if err != nil {
		return nil, err
	}

	responses := make([]*dto.OrderitemResponse, len(entities))
	for i := range entities {
		responses[i] = dto.OrderitemToResponse(&entities[i])
	}

	return &dto.OrderitemListResponse{
		Data:   responses,
		Total:  int(total),
		Offset: qry.Offset,
		Limit:  qry.Limit,
	}, nil
}
