// Package tests provides comprehensive unit tests for the Order Service.
//
// # Overview
//
// This package contains unit tests for all components of the Order Service,
// following the Domain-Driven Design (DDD) and CQRS patterns used in the
// application architecture.
//
// # Test Organization (DDD Layer Structure)
//
// Tests are organized by DDD layers in separate subpackages:
//
//	tests/unit/
//	├── domain/           - Domain layer tests
//	│   └── entity_test.go       - Domain entity tests (Base, Order, Orderitem)
//	│
//	├── application/      - Application layer tests
//	│   ├── command_test.go      - CQRS command tests (Create, Update, Delete)
//	│   ├── queries_test.go      - CQRS query tests (GetByID, GetAll, List, Search)
//	│   ├── handler_test.go      - Application handler tests (Command & Query)
//	│   ├── dto_test.go          - Data Transfer Object conversion tests
//	│   └── query_test.go        - Additional query tests
//	│
//	├── infrastructure/   - Infrastructure layer tests
//	│   ├── middleware_test.go   - HTTP middleware tests (Auth, RateLimit)
//	│   ├── config_test.go       - Configuration loading tests
//	│   └── http_handler_test.go - HTTP endpoint handler tests
//	│
//	├── pkg/              - Shared package tests
//	│   ├── validator_test.go    - Request validation tests
//	│   └── response_test.go     - HTTP response helper tests
//	│
//	└── telemetry/        - Observability tests
//	    └── telemetry_test.go    - TelemetryFlow SDK integration tests
//
// # Test Patterns
//
// All tests follow these patterns:
//
//   - Table-driven tests for multiple scenarios
//   - Arrange-Act-Assert structure
//   - Mocks using testify/mock for dependencies
//   - Parallel test execution where safe
//   - Benchmark tests for performance-critical code
//
// # Running Tests
//
// Run all unit tests:
//
//	go test ./tests/unit/... -v
//
// Run tests for a specific layer:
//
//	go test ./tests/unit/domain/... -v
//	go test ./tests/unit/application/... -v
//	go test ./tests/unit/infrastructure/... -v
//
// Run tests with coverage:
//
//	go test ./tests/unit/... -cover -coverprofile=coverage.out
//
// Run benchmarks:
//
//	go test ./tests/unit/... -bench=. -benchmem
//
// # Test Fixtures
//
// Test fixtures and sample data are available in the tests/fixtures package.
// Mock implementations are available in the tests/mocks package.
//
// # Dependencies
//
// Tests use the following external packages:
//
//   - github.com/stretchr/testify/assert - Assertions
//   - github.com/stretchr/testify/require - Fatal assertions
//   - github.com/stretchr/testify/mock - Mocking framework
//   - github.com/labstack/echo/v4 - HTTP testing
//   - net/http/httptest - HTTP test utilities
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package tests
